<a href="https://colab.research.google.com/github/MihaelaCatan04/Sigmoid_Deep_Dive/blob/main/Lesson_1/Lesson_1_Classwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sigmoid Deep Dive Lesson 1**

## **Classwork**

Install Pytorch according to your computer configurations:



In [ ]:
!pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121


Import Pytorch.

In [ ]:
import torch

### Tensors

Create an one-dimensional tensor of one element.

In [ ]:
a = torch.randn(())

In [ ]:
a

tensor(0.3761)

Create an one-dimensional tensor of 5 element.

In [ ]:
a = torch.randn((5))
a

tensor([ 8.5435e-01, -1.0166e-03, -5.2493e-01, -1.0521e+00,  4.7809e-01])

Create an two-dimensional tensor, with each dimension having size of 5.

In [ ]:
a = torch.randn((5,5))
a

tensor([[-0.4637,  0.3494, -0.3135, -0.2611, -0.3754],
        [-0.1195,  1.2843,  1.4636,  0.5465,  0.2785],
        [ 2.3018,  1.2715, -1.2522,  1.5910, -2.0346],
        [ 1.9173,  0.3965,  0.5355, -0.2324, -0.0093],
        [ 0.6339,  1.7320,  0.4208,  0.0266,  0.2553]])

Transpose the tensor:

In [ ]:
a.T

tensor([[-0.4637, -0.1195,  2.3018,  1.9173,  0.6339],
        [ 0.3494,  1.2843,  1.2715,  0.3965,  1.7320],
        [-0.3135,  1.4636, -1.2522,  0.5355,  0.4208],
        [-0.2611,  0.5465,  1.5910, -0.2324,  0.0266],
        [-0.3754,  0.2785, -2.0346, -0.0093,  0.2553]])

Create a 2-dimensional tensor with 2 rows and 5 columns.

In [ ]:
a = torch.randn((2,5))
a

tensor([[ 1.0076, -0.0614, -0.3399,  2.2952,  1.4540],
        [ 0.4147, -0.6130,  0.2322, -0.0215, -0.2629]])

Transpose this tensor:

In [ ]:
a.T

tensor([[ 1.0076,  0.4147],
        [-0.0614, -0.6130],
        [-0.3399,  0.2322],
        [ 2.2952, -0.0215],
        [ 1.4540, -0.2629]])

### NumPy

In [ ]:
import numpy as np
import math

# Create random input and output data
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

# Randomly initialize weights
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6
for t in range(2000):
  # Forward pass: compute predicted y
  # y = a + b x + c x^2 + d x^3
  y_pred = a + b * x + c * x ** 2 + d ** 3

  # Compute and print loss
  loss = np.square(y_pred - y).sum()
  if t % 100 == 99:
    print(t, loss)

  # Backprop to compute gradients of a, b, c, d with respect to loss
  grad_y_pred = 2.0 * (y_pred - y)
  grad_a = grad_y_pred.sum()
  grad_b = (grad_y_pred * x).sum()
  grad_c = (grad_y_pred * x ** 2).sum()
  grad_d = (grad_y_pred * x ** 3).sum()

  # Update weights
  a -= learning_rate * grad_a
  b -= learning_rate * grad_b
  c -= learning_rate * grad_c
  d -= learning_rate * grad_d

print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')

99 4848.981798368787
199 91014.98446591239
299 559926.5394590897
399 2121183.8813391947
499 6123630.438657623
599 14777512.06993843
699 31351284.12212213
799 60341953.37457506
899 107619691.92353244
999 180548036.82978934
1099 288081758.5944731
1199 440845073.16602343
1299 651193092.5728812
1399 933259328.6188388
1499 1302991812.8870893
1599 1778180073.7876422
1699 2378474875.939269
1799 3125402309.1070466
1899 4042373527.330544
1999 5154691188.996477
Result: y = 2583.7167834089196 + 0.3035076595375481 x + 400.5657417077842 x^2 + -17.093307684108964 x^3


### PyTorch

In [ ]:
import torch
import math
dtype = torch.float
device = torch.device("cuda:0")

# Create random input and output data
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

# Randomly initialize weights
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(2000):
  # Forward pass: compute predicted y
  y_pred = a + b * x + c * x ** 2 + d * x ** 3

  # Compute and print loss
  loss = (y_pred - y).pow(2).sum().item()
  if t % 100 == 99:
    print(t, loss)

  # Backprop to compute gradients of a, b, c, d with respect to loss
  grad_y_pred = 2.0 * (y_pred - y)
  grad_a = grad_y_pred.sum()
  grad_b = (grad_y_pred * x).sum()
  grad_c = (grad_y_pred * x ** 2).sum()
  grad_d = (grad_y_pred * x ** 3).sum()

  # Update wieghts using gradient descent
  a -= learning_rate * grad_a
  b -= learning_rate * grad_b
  c -= learning_rate * grad_c
  d -= learning_rate * grad_d

print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')

99 3518.38818359375
199 2484.0947265625
299 1754.9794921875
399 1240.874267578125
499 878.293212890625
599 622.522216796875
699 442.06097412109375
799 314.7117919921875
899 224.826904296875
999 161.37466430664062
1099 116.57503509521484
1199 84.94013214111328
1299 62.59839630126953
1399 46.817813873291016
1499 35.67021942138672
1599 27.794553756713867
1699 22.229875564575195
1799 18.297679901123047
1899 15.518774032592773
1999 13.554750442504883
Result: y = 0.07232369482517242 + 0.8486678004264832 x + -0.012477039359509945 x^2 + -0.09218207001686096 x^3


Torch.Dataset == Pandas.DataFrame

In [ ]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [ ]:
def yield_something(lst):
  for x in lst:
    yield x

# The function that has the word yield creates a generator

generator = yield_something([1, 2, 3, 4, 5])

In [ ]:
next(generator)

1

In [ ]:
next(generator)

2

In [ ]:
next(generator)

3

In [ ]:
next(generator)

4

In [ ]:
next(generator)

5

In [ ]:
next(generator)

StopIteration: 

In [ ]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download tes data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

In [ ]:
training_data[0]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0000, 0.0510,
           0.2863, 0.0000, 0.0000, 0.0039, 

In [ ]:
batch_size = 64
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
  print(f"Shape of X: {X.shape}")
  print(f"Shape of y: {y.shape}")
  break

Shape of X: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64])


64 - batchsize

1 - no of channels

28 - no of horizontal pixels

28 - no of vertical pixels


In [ ]:
# next(iter(train_dataloader))

In [ ]:
device = (
    "cuda" if torch.cuda.is_available()
    else "mps" if torch.mps.is_available()
    else "cpu"
)

In [ ]:
print(f"Your laptop is using {device}")

Your laptop is using cuda


In [ ]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28, 512),
        nn.ReLU(),
        nn.Linear(512, 512),  # Linear - the connection between 2 neuron layers
        nn.ReLU(),
        nn.Linear(512, 10) # 10 neurons because we have 10 labels
    )

  def forward(self, x):
    x = self.flatten(x)
    predictions = self.linear_relu_stack(x)
    return predictions

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [ ]:
loss_func = nn.CrossEntropyLoss() # CrossEntropy is used for classification tasks
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
# SGD => Stochastic Gradient Descent
# parameters => parameters from each neuron
# lr => learning rate

In [ ]:
def train(dataloader, model, loss_fn, optimizer):
  size = len(dataloader.dataset)
  model.train()
  for batch_no, (X, y) in enumerate(dataloader):
    X, y = X.to(device), y.to(device) # send data to GPU

    pred = model(X) # forward() is called automatically
    loss = loss_fn(pred, y)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if batch_no % 100 == 0:
      loss, current = loss.item(), (batch_no + 1) * len(X)
      print(f"Loss: {loss:>7f} [{current:>5d}/{size:>5d}]")

In [ ]:
def test(dataloader, model, loss_fn):
  size = len(dataloader.dataset)
  num_batches = len(dataloader)
  model.eval()
  test_loss, correct = 0, 0
  with torch.no_grad():
    for X, y in dataloader:
      X, y = X.to(device), y.to(device)
      pred = model(X)
      test_loss += loss_fn(pred, y).item()
      correct += (pred.argmax(1) == y).type(torch.float).sum().item()
  test_loss /= num_batches
  correct /= size
  print(f"Test error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [ ]:
epochs = 5
for epoch in range(epochs):
  print(f"Epoch {epoch+1}\n------------------------------")
  train(train_dataloader, model, loss_func, optimizer)
  test(test_dataloader, model, loss_func)
print("DONE!")

Epoch 1
------------------------------
Loss: 2.293968 [   64/60000]
Loss: 2.298851 [ 6464/60000]
Loss: 2.297110 [12864/60000]
Loss: 2.307167 [19264/60000]
Loss: 2.308490 [25664/60000]
Loss: 2.298764 [32064/60000]
Loss: 2.294288 [38464/60000]
Loss: 2.296173 [44864/60000]
Loss: 2.298520 [51264/60000]
Loss: 2.296357 [57664/60000]
Test error: 
 Accuracy: 12.6%, Avg loss: 2.301339 

Epoch 2
------------------------------
Loss: 2.293968 [   64/60000]
Loss: 2.298851 [ 6464/60000]
Loss: 2.297110 [12864/60000]
Loss: 2.307167 [19264/60000]
Loss: 2.308490 [25664/60000]
Loss: 2.298764 [32064/60000]
Loss: 2.294288 [38464/60000]
Loss: 2.296173 [44864/60000]
Loss: 2.298520 [51264/60000]
Loss: 2.296357 [57664/60000]
Test error: 
 Accuracy: 12.6%, Avg loss: 2.301339 

Epoch 3
------------------------------
Loss: 2.293968 [   64/60000]
Loss: 2.298851 [ 6464/60000]
Loss: 2.297110 [12864/60000]
Loss: 2.307167 [19264/60000]
Loss: 2.308490 [25664/60000]
Loss: 2.298764 [32064/60000]
Loss: 2.294288 [38464/600

In [ ]:
torch.save(model.state_dict(), "model.pth")
print("Saved PyTorch Model State to model.pth")

Saved PyTorch Model State to model.pth


In [ ]:
model = NeuralNetwork().to(device)
model.load_state_dict(torch.load("model.pth"))

<ipython-input-37-b4ef1eff0e4c>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load("model.pth"))


<All keys matched successfully>

In [ ]:
classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot"
]

model.eval()
X, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
  X = X.to(device)
  pred = model(X)
  predicted, actual = classes[pred[0].argmax(0)], classes[y]
  print(f"Prdicted: {predicted}, Actual: {actual}")

Prdicted: Shirt, Actual: Ankle boot
